### ISSUE TITLE
in py311 mod_wsgi-express  install-module crashes

### ISSUE THREAD

**Issue by ReimarBauer** [conda-forge/mod_wsgi-feedstock#24]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

```
root@demo-system:/etc/apache2/mods-enabled# /home/user/Miniforge/envs/mssenv/bin/mod_wsgi-express  install-module
Traceback (most recent call last):
  File "/home/user/Miniforge/envs/mssenv/bin/mod_wsgi-express", line 11, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/user/Miniforge/envs/mssenv/lib/python3.11/site-packages/mod_wsgi/server/__init__.py", line 3843, in main
    cmd_install_module(args)
  File "/home/user/Miniforge/envs/mssenv/lib/python3.11/site-packages/mod_wsgi/server/__init__.py", line 3779, in cmd_install_module
    shutil.copyfile(where(), target)
  File "/home/user/Miniforge/envs/mssenv/lib/python3.11/shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib64/httpd/modules/mod_wsgi-py311.cpython-311-x86_64-linux-gnu.so'
```

When using the version from pypi there is not such an error

### Installed packages

```shell
TBD
```

### Environment info

```shell
TBD
```

**Comment by ReimarBauer** [comment]
it seems not to get that the apache2 dir is 

/usr/lib/apache2/modules/

**Comment by akrherz** [comment]
closing as stale, happy to reopen if not.
